### PR TITLE
FOSSASIA 2017 list

### PR DESCRIPTION
**Pull request by alvations**
Please give me a thumbs up so that we can merge this PR =)

To view the list: https://github.com/alvations/awesome-community-curated-nlp/tree/alvations-2017-fossasia

### CODE REVIEW

**Comment by davidsbatista** [comment]
@alvations I've been collecting all the free and open datasets of annotated semantic relationships:

https://github.com/davidsbatista/Annotated-Semantic-Relationships-Datasets

Do you want to open a section Datasets, or you want to keep this list for tools/software only?

**Comment by alvations** [comment]
@davidsbatista Cool list!

I have another list for datasets stashed away but maybe we can keep this as another file. Otherwise scrolling through resources might be a little more tedious. Let's merge this PR first and I'll create another for dataset =)

**Comment by davidsbatista** [comment]
Yes, let's start another list  for NLP datasets, for different tasks.

**Comment by proycon** [comment]
Some minor issues under "Annotation Platforms":
*  FoLiA should be named "FLAT: FoLiA Linguistic Annotation Tool"  (FoLiA is the name of the underlying format, not the annotation platform ;) )
 * ucto should better be moved to the pre-processing (tokenisation) section, it's a tokeniser and not an annotation platform.

Thanks for including them by the way!

**Comment by proycon** [comment]
Two other suggestions for improvement:
 * I'm not sure about the current categorization, it's a bit too generic/ad-hoc perhaps?
 * It would be nice to include a short description for each tool, so you can more easily identify what it does.

**Comment by alvations** [comment]
@proycon Thanks for the suggestions!!

> I'm not sure about the current categorization, it's a bit too generic/ad-hoc perhaps?

Perhaps for another PR but I agree, it should be more specific but we'll see how the list "evolves" =)


> It would be nice to include a short description for each tool, so you can more easily identify what it does.

Yes, I'll try my best to add 1 sentence / title descriptions to the tools.

@everyone Thank you all for the votes/thumbs-up!! There's >5 votes now =) 
I'll merge it once I get the 1 sentence descriptions done over the weekend!

**Comment by alvations** [comment]
@proycon, about: 

> It would be nice to include a short description for each tool, so you can more easily identify what it does.

I've tried adding short descriptions but the list becomes extremely blotted. I've also tried using 1-2 sentence to describe them  but it does a injustice to the libraries, esp. some of the larger ones that does quite a lot. Been pondering what to do about that. 

~Maybe just better categorization would help. So let's merge it and then reorganize the categories?~

**Comment by davidsbatista** [comment]
Merge it, you already have the 5 thumbs ups.

**Pull request merged**
